### ISSUE TITLE
Scaling seems to be broken

### ISSUE THREAD

**Issue by jonnius** [timsueberkrueb/switch-reloaded#5]
I am on latest dev channel the scaling seems to be broken. the text is huge.

**Comment by timsueberkrueb** [comment]
Yep, thanks for reporting.
My scaling workaround for OTA-4 conflicts with the actual fix, now that it's fixed in the OTA-5 image.

**Comment by timsueberkrueb** [comment]
To fix this, basically https://github.com/timsueberkrueb/switch-reloaded/commit/3c24835907baa6eebd9e5b6cd6c4f1e29229fef6 just needs to be reverted. I think it is reasonable to assume that most people are running OTA-5 by now, since OTA-4 was kind-of a beta-release if I understood it correctly.

**Comment by jonnius** [comment]
Nobody should be running OTA-4 anymore after OTA-5 has been rolled out for some weeks already...
